commands/buy: properly write to file if -o flag is used
a click.File object is not used here, because our logging decorators
require that arguments are serializable as JSON:

TypeError: <unopened file '<FILENAME>' wb> is not JSON serializable

so we have buy() accept a string and manually open it in binary-write
mode in the section where response output is printed